version: '3.8'
services:
  backend:
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    build: ./backend
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PORT=${PORT:-5000}
    volumes:
      - ./path/to/your/ntp.conf:/etc/ntpsec/ntp.conf
    depends_on:
      - mongo
  frontend:
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
  mongo:
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    image: mongo
    ports:
      - "27017:27017"
