version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PORT=${PORT:-5000}
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
  mongo:
    image: mongo
    ports:
      - "27017:27017"
